### PR TITLE
Add Namecheap support

### PR DESCRIPTION
**Pull request by polyzen**
Squashed and rebased #135.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/160)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey @polyzen unfortunately this PR is missing the VCR recordings necessary.
Can you follow the instructions in the CONTRIBUTING.md file and add them?

Thanks!

**Comment by AnalogJ** [comment]
closes #145

**Comment by polyzen** [comment]
I see now. Currently weighing using a different DNS provider or investing in the Namecheap API (hence the PR). Leaning more now towards the prior ;p.

**Pull request closed without merging**
