### PR TITLE
ADD Gehirn Infrastructure Service DNS provider

### PR DESCRIPTION
**Pull request by chibiegg**
This PR will add support for Gehirn Infrastructure Service DNS service.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/181)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey @chibiegg 
Thanks for the PR! The recordings all look great, but I did notice that interacting with records via their identifier is not supported, even though it seems like the responses have identifiers

https://github.com/AnalogJ/lexicon/pull/181/files#diff-cc3bacf9298eeef9640db3db7d992b20R120

Could you provide a bit more information about how record identifiers work with Gehirn?

Thanks!

**Comment by chibiegg** [comment]
Thanks.
OK, I will treat "{recordId}.{base64(content)}" as a identifier.

**Comment by AnalogJ** [comment]
Hmm, sorry I took a look at your new changes. Why are you creating a custom identifier, rather than just using `recordId`. 

The idea behind identifiers is that a user can run `list` and get a full list of DNS records, and then update an individual record by specifying the `identifier` (which would be the `recordId`) and then any fields they would like to update. Same thing for deleting a record.

**Comment by chibiegg** [comment]
So, a identifier in Gehirn is assign to multiple records, then the identifier can not determined the specify record.

For example record id `"d846b5a9-b773-49bb-b263-8a8d7e612ad8"` has 3 records.

```json
{
  "id": "d846b5a9-b773-49bb-b263-8a8d7e612ad8",
  "type": "TXT",
  "name": "somerecord.example.com.",
  "enable_alias": false,
  "ttl": 3600,
  "records": [
    {
      "data": "record1"
    },
    {
      "data": "record2"
    },
    {
      "data": "record3"
    }
  ]
}
```

**Comment by chibiegg** [comment]
Thanks!!
I also made another provider, so please review it. ( #180 ) 🙇‍♀️

**Pull request merged**
