### PR TITLE
[WIP] Updated lexicon

### PR DESCRIPTION
**Pull request by trinopoty**
**DO NOT MERGE**
Updated to use custom exceptions and custom record classes.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/236)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by trinopoty** [comment]
@AnalogJ I've implemented some of the things discussed in #228 . Have a look and suggest.

**Comment by AnalogJ** [comment]
Checking.

**Comment by trinopoty** [comment]
Any updates on this?

**Pull request closed without merging**
