### PR TITLE
add support for Duck DNS

### LINKED ISSUE #1511: DuckDNS.org API support
The DuckDNS.org is a popular Dynamic DNS provider. And it supports the TXT records update which is used for issuing ACME certificates. Here is a sample https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_duckdns.sh
Could you please support it's API?
Also please read the discussion [DNS API standard or specification](https://community.letsencrypt.org/t/dns-api-standard-or-specification/189887)

It also will be nice to support the https://github.com/joohoi/acme-dns/blob/master/README.md

### PR DESCRIPTION
**Pull request by grcancelliere**
closes #1511 

Duck DNS is not a full-fledged DNS implementation, but is still a very popular free dynamic DNS implementation with TXT support for DNS-01 ACME challenges.

### CODE REVIEW

**Comment by grcancelliere** [comment]
@AnalogJ the tests failed because the Azure DevOps pipeline is using a newer tox version which deprecated `whitelist_externals` in favor of `allowlist_externals`. Do you want me to fix it in this branch or should I open a separate PR?

**Comment by stokito** [comment]
Hi @AnalogJ  could you please merge the PR? Even if it contain bugs they won't impact other parts. We'll test it in real life to see if all is fine.

**Review by stokito — APPROVED** [review]

**Comment by adferrand** [comment]
Ok @stokito. I will flag the provider as experimental. I merge and prepare a new release.

**Comment by stokito** [comment]
Thank you

**Pull request merged**
