### PR TITLE
Skip DNSimple accounts that don't have a plan

### LINKED ISSUE #344: DNSimple crash with team member that does not have a plan
Here's the error I get (I have redacted my account number, domain and auth token)

```sh
$ lexicon dnsimple --auth-token REDACTED list REDACTED A
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 64, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/dnsimple.py", line 43, in authenticate
    '/{0}/domains'.format(account['id']), query_params={'name_like': self.domain})
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/base.py", line 87, in _get
    return self._request('GET', url, query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/dnsimple.py", line 189, in _request
    r.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 402 Client Error: Payment Required for url: https://api.dnsimple.com/v2/REDACTED/domains?name_like=REDACTED
```

I believe that this happens because of the way the domain I have is configured. We have a domain configured with a team. There is one account that has a professional plan (with our domain) and we have other users as team members of that account. The only account that has a plan is the one mentioned. Other users have personal accounts by default but they don't have a plan configured at all.

I believe that the code responsible is this: https://github.com/AnalogJ/lexicon/blob/master/lexicon/providers/dnsimple.py#L37-L52

The dnsimple provider iterates through all accounts that the token has access to and tried to see if they have a domain similar to the one specified. When it tries to do this on an account that is not configured it will crash with the http error `402 Client Error: Payment Required for url: ...`.

This is consistent with the documentation from dnsimple: https://developer.dnsimple.com/v2/#response-codes

> `402 Payment Required` - Your account is not subscribed or not in good standing.

I think that it's possible to figure out if an account is not configured by using the `GET /accounts` endpoint. Accounts that are not configured have their `plan_identifier` set to `null`. This does not seem to be documented in the API references tho.

When I do this request I get the following json as output

```json
{
    "data": [
        {
            "created_at": "2018-06-05T19:23:59Z",
            "email": "REDACTED",
            "id": "REDACTED",
            "plan_identifier": "dnsimple-professional",
            "updated_at": "2019-01-06T21:16:40Z"
        },
        {
            "created_at": "2018-06-08T19:48:59Z",
            "email": "REDACTED",
            "id": "REDACTED",
            "plan_identifier": null,
            "updated_at": "2018-06-08T19:48:59Z"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by dotboris**
Fixes #344 

This PR makes it so that accounts that are not configured (don't have a plan) will be skipped when looking for a domain. Since this can lead to pretty convoluted and hard to debug errors, I've added a warning.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/374)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey @dotboris can you fix the lint failures for this PR? Other than that it looks good to go! 🎉

**Comment by dotboris** [comment]
@AnalogJ I think that I've fixed the lint now.

The lint job is still broken but it's `pylint` that crashes and not a linting error. I've tried to run `pylint` locally with little success. 

When I run it through `tux -e lint` it crashes complaining about not being able to install `pylint==2.1.1`. 

I've switched my virtual env to python3 and now `tux` installs `pylint` correctly but it crashes like the CI.

I've tried to install the latest `pylint` and run it locally but it then complains about import errors which the CI does not seem to do.

I've looked through the history of the CI and it seems like that lint job is pretty flaky.

I think that being able to run the linter consistently is something that would improve the contributor experience.

**Comment by adferrand** [comment]
Hello @dotboris, I fixed the pylint issues. You should be able to fix your PR tests with a merge from master.

**Comment by dotboris** [comment]
@adferrand Thanks a bunch for the fixes.

@AnalogJ All the tests & lints pass now

**Pull request merged**
