### PR TITLE
ensure dot in zone:id

### LINKED ISSUE #380: PowerDNS dot notation
From PowerDNS 4.2 onwards, undotted notation is not supported.
From PowerDNS >=4.0 but <=4.1 the dotted notation is _optional_.

I suggest we implement the dotted notation _by default_ since that will work with both dotted and undotted versions. 

We could have a flag to turn this behavior for those running some legacy versions (which doesn't support dotted notation) or simply add support for PowerDNS >=4.0.

### PR DESCRIPTION
**Pull request by splashx**
Closes #380

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/381)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by splashx** [comment]
I want to point out this is passing, the problem is with pylint+tox causing all sort of problems :(
Increasing the version of pylint will create a bunch of false positives for R0801 (see https://github.com/PyCQA/pylint/pull/1055 - which actually didnt solve the problem)

**Comment by adferrand** [comment]
Hello @splashx, I fixed the pylint errors, you should be able to fix your PR tests with a merge from master.

**Comment by splashx** [comment]
@adferrand done. Please review the [AppVeyor CI part](https://ci.appveyor.com/project/AnalogJ/lexicon/builds/24674326) as I think it's not related to these changes.

**Comment by AnalogJ** [comment]
Hey @splashx Thanks for the PR!
Would the `_fqdn_name` helper do the same thing that you're trying to do? 

https://github.com/AnalogJ/lexicon/blob/master/lexicon/providers/base.py#L153

**Comment by splashx** [comment]
@AnalogJ not really. PowerDNS expects the `zone:id` (not the fqdn) in a dot-format.
I also didn’t want to plumb this at a higher level and change `self.domain` because that breaks some logics. So I think this is the appropriate place for this. 
Currently those using lexicon and dealing with PowerDNS must write their own “ensure dot” function and pass that for every zone-handling action. It’s tedious.

**Comment by AnalogJ** [comment]
LGTM. Thanks for the PR @splashx 🎉

**Pull request merged**
