### PR TITLE
Add implementation for ClouDNS provider

### PR DESCRIPTION
**Pull request by ppmathis**
This pull request adds a working implementation of the ClouDNS provider to Lexicon. Recorded cassettes for the test suite are included, as accessing the API requires a paid account.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/141)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
LGTM.

**Comment by AnalogJ** [comment]
Sigh, automation fail. Looks like I'm going to have to fix that before I can merge this 😞

**Comment by AnalogJ** [comment]
This has been languishing long enough. Merging. I'll do a new release manually.

**Comment by ppmathis** [comment]
Thanks a lot for merging! Any chance of getting a new release published soonish?

**Comment by AnalogJ** [comment]
sorry about that. New release is published.

**Pull request merged**
