### PR TITLE
Reallow skipped test for memset provider + provide new cassette

### PR DESCRIPTION
**Pull request by tnwhitwell**
`test_Provider_when_calling_update_record_should_modify_record_name_specified` was skipped before. It is no more.

Also, I've used the `TEST_DOMAIN` more in the cleanup script, which makes life easier when not using capsulecd.com (This one can be dropped if you don't like it)

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/206)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
actually, can you rebase this on the `record_set_support_contrib` branch? I already started doing this there.

**Comment by AnalogJ** [comment]
Hey @tnwhitwell,
Actually this is still wrong. you'll need to close this PR and re-open it against `record_set_support_contrib`

**Comment by tnwhitwell** [comment]
Roger, my mistake. I will rebase and resubmit later today. Sorry!

**Pull request closed without merging**
