### PR TITLE
feat: add qcloud provider

### PR DESCRIPTION
**Pull request by warjiang**
[qcloud](https://www.tencentcloud.com/) is an cloud provider which also provide dns host for user, this pr wants to add support for qcloud.

the api document link: https://cloud.tencent.com/document/product/1427/56194

### CODE REVIEW

**Comment by warjiang** [comment]
fix lint error in cloudflare.py 🍭

**Comment by warjiang** [comment]
@AnalogJ can you help me to review this pr, thanks ~

**Comment by warjiang** [comment]
> @AnalogJ can you help me to review this pr, thanks ~

cc @adferrand

**Comment by warjiang** [comment]
any volunteers to review this pr 😭

**Comment by adferrand** [comment]
Sorry @warjiang for the delay. I look at it.

**Comment by warjiang** [comment]
> Sorry @warjiang for the delay. I look at it.

thanks for your reply, if need more details about this pr, plz comment it down, i'll reply as soon as possible

**Comment by adferrand** [comment]
All good to me, sorry for the huge delay !

**Comment by warjiang** [comment]
> All good to me, sorry for the huge delay !

Thank you for your reply, I'll replace the fork copy with this release one 🚀 . For the problem of delay, if it's possible, I'd like to particate this project, because I'll use this lib for a long time.

**Pull request merged**
