### PR TITLE
add missing exit condition after Yandex Cloud domain retrieval

### PR DESCRIPTION
**Pull request by paskal**
Before that change, dns_zone_id was not used, and cloud_id was used for retrieval every time.

### CODE REVIEW

**Comment by paskal** [comment]
And again, thanks for the tests. They make the expectation of the provider super clear.

**Comment by paskal** [comment]
Gentle ping @adferrand for review.

**Comment by paskal** [comment]
Another gentle ping to @adferrand for review.

**Comment by adferrand** [comment]
Thanks a lot. It makes a better use of the available parameters and less requests at the end. LGTM!

**Pull request merged**
