### PR TITLE
Add Zonomi (and Rimuhosting) name servers support

### PR DESCRIPTION
**Pull request by jarossi**
Lets hope the code is up to standards

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/153)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey @jarossi 
Thanks for the PR!
Hmm, this PR seems to include support for both Zonomi and Rimuhosting in the same file. 

While I don't usually like to have multiple providers supported in the same file, it seems that they both are owned and run by the same company, with the same endpoints. 

Let me think about this a bit.

**Comment by jarossi** [comment]
Correct, similar to the ovh provider, they are the same exact calls for the api but to different endpoints, seems overkill to add another provider when the only thing changing was the api endpoint.
BTW I work for Rimu, and I we are trying to get better support for Letsencrypt going. Also may be worth to cancel this pull request and do another that includes a small change for the authentication method, Let me know, feedback it is appreciated.

**Comment by AnalogJ** [comment]
Hey @jarossi 
It looks good for the most part. The multiple provider thing isn't really a big issue, and it makes sense in this case. 

The uppercase `APIENTRYPOINT` variable is a bit unconventional in python, but its not a big deal
I'm at a conference right now, but I'll merge and release your changes next week.

**Pull request merged**
