### PR TITLE
#387 - Fix path to post request

### PR DESCRIPTION
**Pull request by cmourizard**

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/388)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by caius** [comment]
I've just run into the same bug, and come to the same patch myself. Looks good to me 🙃

**Comment by caius** [comment]
Looks like this is fixed in master, via https://github.com/AnalogJ/lexicon/pull/389

**Comment by adferrand** [comment]
Sorry, did not took the time yesterday to say it, but I fixed the bug and published the release 3.2.0 that contains the fix.

**Pull request closed without merging**
