### PR TITLE
Linode domain case enforcement fix

### PR DESCRIPTION
**Pull request by trinopoty**
This PR fixes linode provider domain name case sensitivity issue.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/459)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey, 
Thanks for the PR @trinopoty 
You bring up a good point, and something that I never really considered.

This PR looks good to merge for linode.

It also looks like we'll need to add another extended test suite to ensure that uppercase and lowercase domain names are correctly handled in all providers. :(

Any feedback on your end @adferrand?

**Comment by trinopoty** [comment]
I actually came across this issue in [#6972 on Certbot](https://github.com/certbot/certbot/issues/6972).
Let me know if you need some test recordings when you add the test suite.

**Comment by adferrand** [comment]
For me this PR LGTM. @trinopoty you can open a PR on Certbot side to update the linode plugin dependency once the new version of Lexicon is opened, I will merge it.

I agree we need to generalize this approach on all providers, and add a test for it. It is not necessary in my opinion on the Linode provider for now, as it will be added globally very soon.

**Comment by trinopoty** [comment]
@adferrand Please let me know when you've released a new version with this PR merged and I'll open the PR on certbot.

**Comment by trinopoty** [comment]
Any updates on getting this merged?

**Comment by AnalogJ** [comment]
I'll trigger a release, sorry for the delay.

**Pull request merged**
