### PR TITLE
Rackspace handle duplicate record on create

### PR DESCRIPTION
**Pull request by rmarscher**
It will now update an existing record if a duplicate exists when
creating. This also fixes the content filter for listing records. Before
this commit, we were not sending the content filter to the proper
data query param documented here:
https://developer.rackspace.com/docs/cloud-dns/v1/api-reference/records/#search-records

However, once the param was updated to the right name, Rackspace was
returning 503 errors for any request that included the data filter.
This seems to be a bug on Rackspace's end. Also tried sending just
a data param without the name param and still received a 503. Also tried
stripping out any non-alphanumeric characters from the content and
still received a 503 (the docs say: Using special characters in a search
 such as " " and "_" causes no results to be returned). I noted these issues
in pull request #189 and ended up closing that pull request because of the
503 errors.

To resolve it, I removed trying to use the content/data filter in the API request.
It fetches the list filtering on type and name and then applies the content filter
on the list in python.

Thank you.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/196)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey @rmarscher 
Can you actually rebase your changes against the `record_set_support` branch in #190?
I've added a couple extra tests that I need recordings for. I also added some instructions in my PR comment that should help you.

**Comment by rmarscher** [comment]
@AnalogJ  I was already working on a rebase against master which I just pushed... but I'll rebase against record_set_support_contrib and update the recordings.

**Comment by rmarscher** [comment]
@AnalogJ  Lol. I see #190 was merged, so I just did one more rebase back to master. All is passing. Let me know if you want it done differently. Thanks! The integration test additions were solid. They catch the bugs that I was fixing with this pull request.

**Comment by rmarscher** [comment]
Sorry... it looks like the accidentally modifies other tests that I didn't touch. Must have been an issue with the rebase. I'll fix.

**Comment by rmarscher** [comment]
OK. That's better. I think this should be good to go. Sorry for all the chatter.

**Comment by AnalogJ** [comment]
Hey @rmarscher 
Sorry, I should have clarified :( You'll need to open a new PR against that branch, github doesn't support changing the base branch for a PR after its been opened.

**Comment by rmarscher** [comment]
Hey @AnalogJ   I'm a little bit confused on what you want. I was going to submit a new pull request against record_set_support_contrib but then I saw that pull 190 was merged to master, so I figured I needed to rebase against the latest master and keep the pull to master.

But if you want it against record_set_support_contrib still, that's fine. I'll create a new pull.

**Pull request closed without merging**
