### PR TITLE
fix easyname html parsing and URLs, fixes #525

### LINKED ISSUE #525: Easyname not working anymore
Lexicon version: 3.3.27

I can't access anything on easyname right now:
```
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/usr/local/lib/python3.6/dist-packages/lexicon/client.py", line 87, in execute
    return self.provider.list_records(record_type, name, content)
  File "/usr/local/lib/python3.6/dist-packages/lexicon/providers/base.py", line 94, in list_records
    return self._list_records(rtype=rtype, name=name, content=content)
  File "/usr/local/lib/python3.6/dist-packages/lexicon/providers/easyname.py", line 190, in _list_records
    return self._list_records_internal(rtype=rtype, name=name, content=content)
  File "/usr/local/lib/python3.6/dist-packages/lexicon/providers/easyname.py", line 217, in _list_records_internal
    rows = self._get_dns_entry_trs()
  File "/usr/local/lib/python3.6/dist-packages/lexicon/providers/easyname.py", line 321, in _get_dns_entry_trs
    'Could not load DNS entries.'
AssertionError: Could not load DNS entries.
```

Credentials are correct. The account is with easyname.at.

### PR DESCRIPTION
**Pull request by pannal**
Easyname have changed their URL schema as well as a couple of parsing-relevant details.

This fixes that.

### CODE REVIEW

**Comment by adferrand** [comment]
Hello @pannal, thanks a lot for finding the issue and provide the PR to fix it!

About the test failures here, the recordings stored in the project to execute the integration tests offline need to be regenerated with the fixed URL calls against the live API. Are you willing to do it, since you have valid credentials for the provider? The procedure is explained here: https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md#test-recordings

**Comment by pannal** [comment]
Sure, let me check.

**Comment by pannal** [comment]
@adferrand what am I missing here? I've built the tests with Py3.6. Do I need to execute any more steps in order for the 3.8 tests to not fail?

**Comment by adferrand** [comment]
Hello @pannal! The other failures are not related to your provider. The project `dnspython` get a major update that breaks the `localzone` provider. It is fixed on master.

I have updated your PR for you, the tests should pass now.

**Comment by adferrand** [comment]
Ok, everything is working! I merge your PR and prepare a new release.

**Pull request merged**
