### PR TITLE
Use poetry-core for build

### PR DESCRIPTION
**Pull request by harens**
This should hopefully close https://github.com/AnalogJ/lexicon/issues/568 by switching from `poetry` to `poetry-core`. See https://github.com/python-poetry/poetry/issues/1975 for more details on the issue.

This is done as recommended by the [Poetry docs](https://python-poetry.org/docs/pyproject/#poetry-and-pep-517):

> If your pyproject.toml file still references poetry directly as a build backend, you should update it to reference poetry_core instead.

I couldn't test this on my machine as a result of https://github.com/pyca/cryptography/issues/3489 occuring with poetry. Hence I marked it as a WIP.

The only thing I'm a bit cautious of is the use of `setuptools` in the build-system. I don't think it's required for `poetry` (see https://github.com/python-poetry/poetry/issues/2956#issuecomment-698334887) but I'm not sure about `poetry-core`. However, there are other projects with a similar setup.py without needing setuptools in the pyproject.toml, such as [rich](https://github.com/willmcgugan/rich), so I thought I'd give it a shot and revert it if necessary.

See https://trac.macports.org/ticket/62682 for full discussion.

### CODE REVIEW

**Comment by harens** [comment]
It seems like tests are failing for unrelated reasons relating specifically to `HTTPERROR` (maybe https://github.com/AnalogJ/lexicon/issues/490?).

**Comment by commonism** [comment]
Glad to see this fails for you as well. 
I'm having the similar issues (#786), but I actually touched relevant authorization code, so … seems like something else broke.

**Comment by adferrand** [comment]
Just to keep you informed that I follow the discussions, I will invest myself as soon as I have some time.

**Review by adferrand — APPROVED** [review]
I update the PR with master, and tests are passing. LGTM!

**Comment by harens** [comment]
Thanks @adferrand.

**Pull request merged**
