### PR TITLE
dnsmadeeasy: Deprecate Babel in favor of std lib

### PR DESCRIPTION
**Pull request by nydr**
Resolves issue #152 

I've never deprecated optional dependencies before so I don't know if there's a proper procedure for that

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/154)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey @nydr 
Thanks for the PR.

In the past, `dnsmadeeasy` was using code like the following to generate the correct string format before HMAC:
- https://github.com/AnalogJ/lexicon/blob/d4d9bfb9a6a828819526548ecbd95032475c2423/lexicon/providers/dnsmadeeasy.py#L134-L139

However that started causing issues during the CI testing, as en_US was unavailable (and it was also setting the locale on a global level). 

I'm not really familiar with `email.utils`, are you certain that it will use the correct locale when generating the timestamp string, even if the user's system language is French, Chinese, etc?

**Comment by nydr** [comment]
Hi @AnalogJ thank you for looking at this PR. `email.utils.formatdate` is not concerned with locales as it's originally meant to be used for RFC2822 dates.

Looking at the implementation it seems to be using a hardcoded list of names for months and weekdays:
https://github.com/python/cpython/blob/2.7/Lib/email/utils.py#L167

After setting the OS language to korean it appears to be working as expected, let me know if you have any additional scenarios I can test
```
root@625aa75611e3:/# echo $LANG
ko_KR.UTF-8
root@625aa75611e3:/# date
2017. 11. 28. (화) 17:49:48 UTC
root@625aa75611e3:/# python -c 'from email.utils import formatdate; print(formatdate(usegmt=True))'
Tue, 28 Nov 2017 17:49:59 GMT
```

**Comment by AnalogJ** [comment]
Hey @nydr 

I actually hadn't heard of `email.utils` before, thats awesome. 
The PR looks good, I'll merge it and release a new version when I get back from the conference I'm currently attending.

**Comment by bmw** [comment]
I agree it's pretty rare. We've been using this project since May and these issues with dnsmadeeasy have been the first problems. With that said, a warning about breaking changes in the API (including breaking changes in `setup.py` affecting installation) would certainly be appreciated and make building on this project easier. I'll try and keep a closer eye on things myself, but a mention on GitHub or an email to bmw@eff.org about future changes like this would help me out a lot.

**Comment by AnalogJ** [comment]
Hey @bmw 
Yeah I can definitely send an email and open an issue to keep you guys updated on any breaking issues.

**Pull request merged**
