### PR TITLE
Hurricane Electric (henet) provider

### PR DESCRIPTION
**Pull request by hank**
I've successfully created and tested (on Python 2.7 and 3.5) an implementation of the Hurricane Electric (lack of) API. Please review, comment, and if you feel it's worthy, merge. I believe I properly followed the CONTRIBUTING doc, but please point out if I failed in any way and I'll be happy to make it right.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/293)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by adferrand** [comment]
Hello @hank, congrats! I also started to write a provider (and suffer on the api) for hurricane yesterday, but you managed to do it with this elegant parsing of the html response ^^

And with the full test suite, which is nice. 

Three observations on the provider code itself:
* you import print_function from __future__ two times,
* you advert about disabling the two-factor authentication in the code as a comment, but it is more relevant to display this to the end user: you could at it in the SubParser class, using its member `subparser.description`. By this way it will be displayed on command line when a user activates the help for this provider.
* you declare an import from `bs4` module, but it is an optional requirement: so it is not always installed, and in this case any call to lexicon will crash, as lexicon need to load all provider modules at start (just for introspection, not executing the code itself). So you need to handle the non existence of the module:
```
try:
   from bs4 import BeautifulSoup
except ImportError:
   pass
```

**Comment by adferrand** [comment]
By the way @Analogj, we should at a test to ensures that lexicon client starts correctly without the optional imports.

**Comment by adferrand** [comment]
Also @hank, you can also update `README.md` to move Hurricane in the supported provider section.

**Comment by AnalogJ** [comment]
Hey @hank 
Thanks for the PR! I see that you've taken @adferrand 's advice and fixed the issues he mentioned. The provider looks good and ready to merge. I'll trigger a new release now. 🎉 

@adferrand Appreciate all the work you've done reviewing PR's and responding to issues 👍 
There actually is a unit test to ensure that lexicon starts correctly without optional dependencies: https://github.com/AnalogJ/lexicon/blob/master/tox.ini#L12

However its only run during release testing: https://github.com/AnalogJ/lexicon/blob/master/capsule.yml#L2 I wasn't familiar enough with tox command line flags to handle dynamic python environments + one static environment during circleci testing

**Pull request merged**
