### PR TITLE
Support pagination from DigitalOcean API 

### LINKED ISSUE #35: Digitalocean Provider spits out invalid json
```
[  
   {  
      'content':u'"v=DKIM1; k=rsa; p=MIGfMA0GC[...redacted...]GUrwFVgQIDAQAB"',
      'id':1256011,
      'type':u'TXT',
      'name':'mesmtp._domainkey.ctnguyen.net',
      'ttl':''
   },
   {  
      'content':      u'"v=spf1 include:spf.messagingengine.com -all"',
      'id':2349116,
      'type':u'TXT',
      'name':'@.ctnguyen.net',
      'ttl':''
   }
]
```

The issued command is ```lexicon digitalocean list ctnguyen.net --auth-token $LEXICON_DIGITALOCEAN_TOKEN TXT```

Look after the `content`-pair and `type`-pair. There are _u_'s after the colon. I don't were there are coming from. 
I discovered this, when I tried to setup letsencrypt.sh with the provided example hook. 
The `clean_challenge` returns an empty list(maybe because the json is invalid).

### PR DESCRIPTION
**Pull request by mrwacky42**
Fixes #35. 
This is branched from #69, so this will be much more readable after that lands.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](http://www.github.com/AnalogJ/capsulecd). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](http://www.capsulecd.com/#!/deploy/github/AnalogJ/lexicon/pullrequests/70)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](http://www.github.com/AnalogJ/capsulecd)

**Comment by AnalogJ** [comment]
Sorry @mrwacky42 I'm travelling right now and I probably wont have time to vet this PR for at least another week. Thanks for the PR though.

**Comment by AnalogJ** [comment]
Hey @mrwacky42 To be honest I'm not completely sold on the linter changes in the #69 PR, especially since they apply only to the Dreamhost provider.  Any chance you could reopen this PR directly against master? I'd be happy to merge it then :)

**Comment by mrwacky42** [comment]
The power of PEP8 compels you!

**Pull request closed without merging**
