### PR TITLE
Filter on Private Zone when searching hosted zone

### LINKED ISSUE #142: Route53: Public and Private Zones can't be distinguished.
I've been testing out lexicon for updating DNS records via Route53, and I have a Public and Private Zone with the same domain name.
I noticed that lexicon is only searching for the domain name by name, so in my case, my internal zone was the first created and so it's the only thing lexicon itself finds for my domain name.

I was going to have it update a record for my home IP address for dynamic IP issues, but what's happening is it is only updating the Private zone's record. I've specified --identifier with the ZoneID of the Public Zone, but that is not working either.

I didn't even have a record for home.mydomain.com in my Private Zone, and it ended up creating the record just to fullfill the update. I do see in the output of lexicon both private and public zones, including the <PrivateZone>true|false</PrivateZone> specifically identifying it as private or not.

I'd like to be able to update both, differently as needed.

### PR DESCRIPTION
**Pull request by Stollie**
Add "--private-zone" argument to only search for Private Hosted Zones when true and Public Hosted zones when false.

Resolves #142

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/147)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by Stollie** [comment]
What can I do to get this pull request merged?
I'm trying to figure out how to add an extra test for route53, but I can't access the 'cassette_library_dir'.

```python
"""Test for route53 implementation of the interface."""
import unittest
import pytest
import vcr
from lexicon.providers.route53 import Provider
from integration_tests import IntegrationTests

# Configure VCR
provider_vcr = vcr.VCR(
        cassette_library_dir='tests/fixtures/cassettes',
        record_mode='new_episodes',
        decode_compressed_response=True
)

class Route53ProviderTests(unittest.TestCase, IntegrationTests):
    """Route53 Proivder Tests."""

    Provider = Provider
    provider_name = 'route53'
    domain = 'capsulecd.com'

    def _filter_headers(self):
        """Sensitive headers to be filtered."""
        return ['Authorization']

    def test_Provider_authenticate_private_zone_only(self):
        with provider_vcr.use_cassette(IntegrationTests._cassette_path('IntegrationTests/test_Provider_authenticate.yaml'), filter_headers=IntegrationTests._filter_headers(), filter_query_parameters=IntegrationTests._filter_query_parameters(), filter_post_data_parameters=IntegrationTests._filter_post_data_parameters()):
            provider = self.Provider(IntegrationTests._test_options(), IntegrationTests._test_engine_overrides())
            options = IntegrationTests._test_options()
            options['private_zone'] = 'true'
            provider.authenticate()
            assert provider.domain_id is None

    @pytest.mark.skip(reason="route 53 dns records don't have ids")
    def test_Provider_when_calling_delete_record_by_identifier_should_remove_record(self):
        return

    # TODO: this should be enabled
    @pytest.mark.skip(reason="regenerating auth keys required")
    def test_Provider_when_calling_update_record_should_modify_record_name_specified(self):
        return`
```

**Comment by AnalogJ** [comment]
Hey @Stollie can you try rebasing your code off of the latest master (or merging the latest master into your branch)? I made some changes to the test engine, and it should correctly load env variables for recordings now.

It looks like you've already read `CONTRIBUTING.md`, but if you want to use `provider_vcr` you'll have to import it from the `IntegrationsTest` class I think. 

try:

    from integration_tests import IntegrationTests, provider_vcr

**Comment by Stollie** [comment]
Thanks for the tip.

I've added two tests using the current 'test_Provider_authenticate' cassette.

**Comment by AnalogJ** [comment]
Awesome, I'll be merging this PR once I tweak my automation bot a bit.

**Pull request merged**
