### PR TITLE
Create a code quality gate for Lexicon

### PR DESCRIPTION
**Pull request by adferrand**
Lexicon sees a lot of external contributors that implements new providers, like myself.

We all have our coding techniques, but I think that everyone is agree about the efficiency to use a linter to enforce code quality.

This PR proposes a specific job in the CI workflow, that executes `pylint` on lexicon codebase (`lexicon` module and `tests`). Upon the generated report, some quality gate controls are done, and the job fails if theses gates are not passed. Here are the quality gates:
* no issue of level "fatal"
* no issues of level "error"
* no global note degradation compared to the master branch of lexicon repository.

I think the two firsts gates are quite obvious, let me develop on the last one.

One could say that a simple rule would be: no pylint issue at all in the code, do not add any bad code through your PRs. But this goal is currently extremely difficult to achieve: there is more than 5000 warning issues in Lexicon codebase. It will take months to remove everything. An even with this, having absolutely no errors in pylint is very restrictive.

Besides, pylint generate an overall note of the code, that does not include only issues about formatting, but also about duplication.

For all of theses reasons, I prefer to work on the note value.

One could consider a threshold on the note, and below it the job would fail. But in a continuous improvment of the code, this threshold should be increased regularly. Cumberstone, and what reference to use ? I think that obsiously, the note on the master upstream is the most appropriate value, to avoid decreasing code quality through the PRs.

This what the last gate does automatically. By checkouting master upstream and executing pylint on it, the global note is taken, and compared to the global note calculated on current code. Then the gate can kicks in.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/310)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey @adferrand can you fix the conflicts in this PR? I think it would be a great addition to the test suite.

**Comment by adferrand** [comment]
All right @AnalogJ, I solved the conflicts.

**Comment by adferrand** [comment]
And again ^^

**Comment by AnalogJ** [comment]
haha, sorry about that. I'll get this merged after the CircleCI tests pass.

**Comment by adferrand** [comment]
Bump, not working. I fix that.

**Comment by AnalogJ** [comment]
Looking at the `localzone` library, it seems the referenced methods actually do exist. Any idea why the linter thinks they are missing?

```

lexicon/providers/localzone.py:50:15: E1101: Instance of 'Zone' has no 'add_record' member (no-member)
lexicon/providers/localzone.py:70:22: E1101: Instance of 'Zone' has no 'find_record' member (no-member)
lexicon/providers/localzone.py:106:19: E1101: Instance of 'Zone' has no 'update_record' member (no-member)
lexicon/providers/localzone.py:130:20: E1101: Instance of 'Zone' has no 'remove_record' member (no-member)
```

**Comment by adferrand** [comment]
Yes I understood. What pylint see is a c

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/310)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Pull request merged**
