### PR TITLE
change transip provider to use transip-api

### PR DESCRIPTION
**Pull request by yorickvP**
I noticed the transip provider was gone, and that there was a [new project](https://github.com/benkonrath/transip-api) providing a transip api.

I'm not sure how to specify the dependency from github, might be useful to put transip-api on pypi. Otherwise, command line usage seems to work and the tests pass. I haven't tried using it with dehydrated yet.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/deploy/github/AnalogJ/lexicon/pullrequests/100)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey @yorickvP 

This pr seems to be using the old `transip` library by LordGaav: https://pypi.python.org/pypi/transip/0.2

Unfortunately the reason I removed it from `lexicon` is that it's not compatible with python 3.x
I'd be willing to merge a PR which specifies the `transip-api` library if it passes the test suite: https://github.com/benkonrath/transip-api

To use a git repo, instead of a pypi library, you can just specify it in the `optional-dependencies.txt` file like so:

`-e git+https://github.com/benkonrath/transip-api.git#egg=transip-api`

**Comment by yorickvP** [comment]
No, this pr uses the new `transip-api`, I just have no idea how to do setuptools dependency management.
benkonrath/transip-api also has the package name `transip`.
I tested it with python3 with `transip-api` installed and it passes the test suite. I added an attempt to specify the dependency to this pull-request, but it should really just be on pypi.

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/deploy/github/AnalogJ/lexicon/pullrequests/100)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hmm, seems I might have misunderstood what you were trying to do. I just saw the `transip` dependency in the `setup.py` file and assumed that you were just reverting the old provider. 

I've reopened the PR. Let me take a look at this branch and get back to you.

**Comment by AnalogJ** [comment]
Hey @yorickvP 
I made some modifications to your branch to get everything working with the optional dependencies.
Its merged, and a new release has been created, v1.2.4

Thanks!

**Pull request merged**
