### PR TITLE
Adding a new hetzner provider compatible with dns.hetzner.com

### PR DESCRIPTION
**Pull request by l0rn**
Hetzner added a new DNS API while simultaniously shutting down their old
web based "Domain Robot" which was formerly implmented in lexicon
using web scraping. As far as i can see that "Domain Robot" is shut down for
good making the old Hetzner provider for this tool obsolete - BUT;
The old Hetzner provider does supply two modes, one for the obsolete robot,
one for Hetzner's konsoleH, which is their shared hosting offering, which
remains (for now?).

I moved the old web scraping based Hetzner provider to hetzner_konsoleh

~I probably would opt for deleting the really obsolete "Domain Robot" part
of the old Hetzner provider and rename it to hetzner_konsoleh.~

I would actually opt for deleting everything from the old hetzner provider, as the "robot" variant is obsolete and the konsoleh is dysfunctional because of changes to the DOM and I would argue it's unfeasable to adapt and rather would go for dropping support - but I am waiting for feedback of the maintainers.

### CODE REVIEW

**Comment by l0rn** [comment]
This should solve #491

**Comment by qqilihq** [comment]
Awesome. We’ll be really looking forward to this!

**Comment by wizison** [comment]
Also looking forward to this! :)

**Comment by pp0815** [comment]
With branch 09986f6 the variable PROPAGATED in **dehydrated.default.sh** throws an error. Simply removing it helps.

I think the hole special handling for PROVIDER = hetzner is obsolete now.

But at the moment i can not test it, sorry.

**Comment by l0rn** [comment]
yeah, i would opt for scrapping everything related to hetzner providers relying on web scraping

**Comment by l0rn** [comment]
Is there any hope we can get this looked at soon?

**Comment by adferrand** [comment]
I am completely overwhelmed until tomorrow, but after this I am available. You can expect this done by the end of this week.

**Comment by qqilihq** [comment]
@l0rn @adferrand I just set this up -- this works great! Thank you so much!!!

**Comment by dual-oo** [comment]
@adferrand works perfect and really fast. thanks!
btw: the dehydrated example is now deprecated

**Comment by level420** [comment]
> @adferrand works perfect and really fast. thanks!
> btw: the dehydrated example is now deprecated

Sorry for asking: could you please share your (of course anonymized) config for dehydrated and the new hetzner DNS? that would be great!

**Comment by level420** [comment]
Here is the needed configuration for dehydrated in conjunction with the hook script from here #505 
https://github.com/AnalogJ/lexicon/pull/505#issuecomment-624614864

**Comment by dagirgl** [comment]
Thank you very much for this! Works really fast! And also for/with dehydrated. But one thing I can't figure out: How do you update the "master" A-record? I tried:

`lexicon hetzner update example.com A --name='@.example.com' --content="[newIP]" --auth-token=[hetznerAuthToken]`

and

`lexicon hetzner update example.com A --name='@' --content="[newIP]" --auth-token=[hetznerAuthToken]` 

But that fails with error msg:
`requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://dns.hetzner.com/api/v1/records/[recordId]`

I also tried to escape the at-sign, but that's not the problem here, I think.
Works for `--name="www"`,  or `--name="www.example.com"` and all other record-names. What am I doing wrong? Sorry for this maybe stupid question...

**Pull request merged**
