### PR TITLE
Use Bearer Token Authorization for Cloudflare API Tokens

### PR DESCRIPTION
**Pull request by acortelyou**
#425 Support Cloudflare API tokens

`py.test lexicon/tests/providers/test_cloudflare.py` passes.

`lexicon cloudflare list <domain> A` returns expected results.

Unfortunately, it looks like an API Token cannot be scoped to specific zone otherwise the following call will fail even if scoped to the `<domain>` zone.

`GET https://api.cloudflare.com/client/v4/zones?name=<domain>&status=active`

Perhaps there could be a workaround to avoid that call **or someone could slap some sense into Cloudflare.**

For now this appears to work for tokens with the `Zone.Zone` and `Zone.DNS` permissions in `All zones`.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/460)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by acortelyou** [comment]
I have discovered you are able to scope the token to the appropriate zone if you additionally grant the `Account.Account Settings:read` permission which implicitly grants `com.cloudflare.api.account.zone.list`.

Cloudflare has a hole in their API which prevents retrieving `Zone Details` by name unless you have the `Zone List` permission with which to resolve the name to an ID.

**Comment by AnalogJ** [comment]
Hey @acortelyou 
Thanks for the PR! 🎉 

I'd like to see a test suite running with API token credentials just to verify that everything is working correctly.

You can add a secondary test suite similar to what (we do in the Gandi provider test suite)
https://github.com/AnalogJ/lexicon/blob/master/lexicon/tests/providers/test_gandi.py

Thanks!

**Comment by yonathan9669** [comment]
Hello guys, I've been trying to use the API-TOKEN but noticed you didn't support it yet, it would be awesome if you actually merge this finally and update the documentation accordingly to understand you use the `global_api_key` instead of the `api_token`. I wanna use this feature with adferrand/dnsrobocert#78  but as noticed there, I've been having issues with the `global_api_key` too.

**Comment by adferrand** [comment]
Hello @acortelyou, are you willing to finish this PR? If not, are you ok with me to take it over?

**Comment by acortelyou** [comment]
@adferrand That would be great, I don't have the time to add tests at the moment.

**Comment by adferrand** [comment]
We are all set! Thanks again @acortelyou!

**Comment by nightah** [comment]
@adferrand what’s the typical process and turnaround for these changes to propagate to dnsrobocert?

**Comment by adferrand** [comment]
Don't worry, I am part of the Certbot development team, maintainer of Lexicon and DNSroboCert. So things propagate quite quickly on that matter ;)

I am preparing right now a new release of Lexicon, and will do update DNSroboCert as soon as Certbot 1.4.0 is released since we are also in the middle of its release process.

**Pull request merged**
