### PR TITLE
[WIP] Godaddy provider

### PR DESCRIPTION
**Pull request by jacobsantos**
I spent enough time to spec out how the code should be. I am unsure how to test locally. The Dockerfile does not use the local files. I could setup a virtual environment, but I'm not that familiar with Python or at least I haven't yet done that with an existing Python project.

Submitting this for others to test. Also for feedback. Seems to be exactly what I need, so any guidance on getting this in would be appreciated.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](http://www.github.com/AnalogJ/capsulecd). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](http://www.capsulecd.com/#!/deploy/github/AnalogJ/lexicon/pullrequests/78)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](http://www.github.com/AnalogJ/capsulecd)

**Comment by AnalogJ** [comment]
Hey @jacobsantos, thanks for the PR. 
Yeah, I should add a section to the README specifying how developers can write and test their own providers. 

I'm traveling currently, but once I'm back next week I'll take a look at your PR and fix the missing test suite.

👍

**Comment by txr13** [comment]
This would be super-helpful for me, as well. Definitely willing to help test it!

**Comment by AnalogJ** [comment]
Hey @jacobsantos 

Thanks for the PR. I finally got around to putting a [contributing.md](https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md) guide together. It has instructions on how to write a provider, manually test it and run it through the integration suite (with VCRpy recordings).

Can you take a look and update your PR with the VCRpy recordings? Then I can merge your PR immediately :)

**Comment by AnalogJ** [comment]
@jacobsantos ping :)

**Comment by AnalogJ** [comment]
Closing this, there doesn't seem to be any activity.

**Pull request closed without merging**
