### PR TITLE
Add DirectAdmin Provider

### PR DESCRIPTION
**Pull request by bauglir**
This adds support for DirectAdmin DNS management, at least the version I have access to on my hosting provider (v1.57.2).

As there is no fixed domain where these are hosted, this adds a parser argument to specify the root endpoint of the DirectAdmin instance to use. I wasn't sure if there was a specific way to specify these arguments as mandatory. So currently, an error gets thrown when it's not specified on instantiation of the provider.

As this needed to run against a real domain/host I own, I scrubbed the vcrpy recordings for potentially sensitive data.

Looking forward to any feedback.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/418)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by bauglir** [comment]
I have fixed the linting issues. The root cause of why the Python 3 tests are failing is a mystery to me though. I'm not that familiar with the Python ecosystem, so have been struggling a bit with running the tests for Python 3 locally. Any pointers would be appreciated.

**Comment by bauglir** [comment]
It looks like recording the HTTP interactions using Python 3 works fine when replaying them on Python 2, but not the other way around. All checks are passing now (uncovered pieces of code are all related to exceptions and warnings).

Might make sense to mention this in the contribution guidelines, as currently, the [Getting Started section](https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md#getting-started) seems to favor starting out with Python 2.7.

**Comment by AnalogJ** [comment]
Hey @bauglir Thanks for the PR! 🎉 

Yeah, as you've noticed our development setup instructions are definitely Python 2 centric. I'll add a note about creating the recordings with Python 2 to the CONTRIBUTING.md file. 

I'll try to take a look at your PR and provide some feedback later today.

-Jason

**Comment by bauglir** [comment]
Thanks Jason!

Looking forward to the review. Overall I found the `CONTRIBUTING.md` file very clear and a very nice guide for writing a new provider. This was the one minor thing that tripped me up. Also likely because I was scrubbing the recordings from sensitive data manually, so it may have just been me :)

**Comment by adferrand** [comment]
If everything works better if the development is done on Python3, maybe we should make the development instructions Python 3 centric. As Python 2.7 will be EOL by the end of the year, maybe it is a good first step for the migration.

**Comment by bauglir** [comment]
Thanks for the merge. No worries about the delay, happy to have been able to help out! Looking forward to using the provider :)

**Pull request merged**
