### PR TITLE
Fixes easyname integration

### PR DESCRIPTION
**Pull request by o-sole-meo**
This fixes the easyname integration. Apparently they changed their website.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/449)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by o-sole-meo** [comment]
Could it be that the checks are not successful because there is no username+password present? lexicon works without any problems on my end including the fixes.

**Comment by adferrand** [comment]
No I think it is because the cassettes have diverged. The idea is that we cannot rerun the integration tests against the real API providers each time a CI pipeline is triggered, because the performances would be bad, we do not have the credentials used by each contributor to validate the initial implementation of each provider.

Instead we use vcrpy, a HTTP request mock solution that replace the real API providers. Instead, vcrpy will return the response for each request done as saved in the cassettes located at `tests/fixtures/cassettes`.

However to make this system works, the cassettes must reflect exactly each interaction the Lexicon provider would have with the real API. Each logic changed in the provider that impacts this interaction require a new recording of the cassettes against the real provider API.

This is the case here.

Since you have credentials for `easyname`, could you do it? Everything is explained here: https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md#test-recordings

Thanks in advance!

**Comment by o-sole-meo** [comment]
Hi,

Sorry for not reading the Contributing Guidelines, figured its only a few characters that changed, so what the hell ^^

Anyway I am in the process of recording the cassete. There is an Error ocurring and I cannot figure out why. Maybe you can help me.

```
___________________ EasynameProviderTests.test_provider_when_calling_list_records_with_name_filter_should_return_record ____________________

self = <test_easyname.EasynameProviderTests testMethod=test_provider_when_calling_list_records_with_name_filter_should_return_record>

    @_vcr_integration_test
    def test_provider_when_calling_list_records_with_name_filter_should_return_record(self):
        provider = self._construct_authenticated_provider()
        provider.create_record('TXT', 'random.test', 'challengetoken')
        records = provider.list_records('TXT', 'random.test')
        assert len(records) == 1
        assert records[0]['content'] == 'challengetoken'
        assert records[0]['type'] == 'TXT'
>       assert records[0]['name'] == 'random.test.{0}'.format(self.domain)
E       AssertionError

lexicon/tests/providers/integration_tests.py:184: AssertionError
```

When I test for the TXT record I can see it though:

```
lexicon easyname --auth-username user --auth-password 'pass' list meo-energy.com TXT --name "random.test.domain.com" --content "challengetoken"
ID      TYPE NAME                       CONTENT        TTL 
------- ---- -------------------------- -------------- ----
7836686 TXT  random.test.domain.com challengetoken 3600

```

**Comment by rqelibari** [comment]
I think we can close this PR in favor of #467.

**Pull request closed without merging**
