### PR TITLE
Update pytest to 4.x

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/354)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by adferrand** [comment]
Hello, and thanks for your PR!

I am thinking that keeping software up-to-date toward its external dependencies is a sufficient reason on its own to do the development efforts. In particular on tests dependencies that are free of retro compatibility considerations.

However, I would also be interested to see your motivations to make the efforts, push theses updates in Lexicon and handle the migration path. Also, as there are several major upgrade of the third-party components, I would also be interested to read a short summary from you of the interesting capabilities that theses new version would offer to Lexicon.

Would you have the time for that ?

Beside that, it is technically LGTM, and will be merged very soon. Thanks !

**Comment by felixonmars** [comment]
Thanks. I am packaging lexicon for Arch Linux (as a dependency of certbot). Since we have the latest pytest the test suite is currently broken without the change :)

**Comment by adferrand** [comment]
Since `get_closest_marker` has been introduced in Pytest 3.6.0, I think we have a reasonable retro compatibility cover on recent Pytest 3.x if other dependent projects reuse Lexicon tests. Breaking changes will eventually appear, but not until a significant amount of time that will let everyone move to Pytest 4.x.

Merging, and new release!

**Pull request merged**
