### PR TITLE
Test suite fixes for #182, Record set support & duplicate record noop testing. 

### LINKED ISSUE #138: Namesilo throwing an exception on create if a record already exists
The Namesilo provider halts with an exception on create if a record already exists. The comment suggests that it should be doing nothing if the record already exists.

Let's Encrypt dns-01 validation doesn't seem to work with wildcard A records, so the theory here is to have my hook create an A/AAAA record when issuing a cert. However the exception prevents this from being possible.

### LINKED ISSUE #182: Support multiple records of the same type on an identifier
In [certbot](https://github.com/certbot/certbot), we use lexicon to create TXT records for a domain to prove to a SSL/TLS certificate authority that the user has control over that domain so the CA will give you a certificate which you can use to set up HTTPS. Due to the way [the protocol](https://tools.ietf.org/html/draft-ietf-acme-acme-09) works, we sometimes have to set multiple TXT records for a single domain.

I'm not sure if each of the providers we use have problems with creating multiple TXT records on a domain (although I know this works with your code for dnsimple), but they all have problems deleting it and immediately error out if there is more than 1 record for the domain:

* [cloudxns](https://github.com/AnalogJ/lexicon/blob/a8c478ad44c06012c3aaaac077f70e67c12a136e/lexicon/providers/cloudxns.py#L125)
* [dnsimple](https://github.com/AnalogJ/lexicon/blob/903af58378ab9942d817c57e0330b5f7ac26b4e9/lexicon/providers/dnsimple.py#L128)
* [dnsmadeeasy](https://github.com/AnalogJ/lexicon/blob/9ad8a9cbf9e4b5c24fe525b274966c2432baf132/lexicon/providers/dnsmadeeasy.py#L121)
* [luadns](https://github.com/AnalogJ/lexicon/blob/a8c478ad44c06012c3aaaac077f70e67c12a136e/lexicon/providers/luadns.py#L98)
* [nsone](https://github.com/AnalogJ/lexicon/blob/8b649338b6c03c7bfb2d465249cd759de62296cb/lexicon/providers/nsone.py#L175)

Can support for this be added?

### PR DESCRIPTION
**Pull request by AnalogJ**
Still work in progress. 

The providers which need recordings are as follows:

- [x] aurora - contributed by @joostdebruijn
- [x] cloudflare
- [ ] cloudns - contributed by @ppmathis
- [x] cloudxns
- [x] digitalocean
- [x] dnsimple
- [x] dnsmadeeasy
- [ ] dnspark
- [ ] dnspod
- [ ] easydns
- [ ] gandi - contributed by @hrunting
- [ ] gehirn - contributed by @chibiegg
- [ ] glesys - contributed by @hecd
- [ ] godaddy - contributed by @adferrand
- [x] linode
- [x] luadns
- [x] memset - contributed by @tnwhitwell
- [ ] namecheap - contributed by @pschmitt
- [x] namesilo
- [x] nsone - **paid account - need contributor**
- [ ] ovh - contributed by @adferrand
- [x] pointhq
- [ ] powerdns - contributed by @insertjokehere
- [ ] rackspace - contributed by @rmarscher
- [x] rage4
- [ ] route53 - contributed by @eadmundo
- [ ] sakuracloud - contributed by @chibiegg 
- [ ] softlayer - contributed by @adherzog 
- [ ] transip - contributed by @LordGaav @yorickvP
- [ ] vultr - **paid account - need contributor**
- [x] yandex
- [ ] zomomi - contributed by @jarossi 

fixes #182 
fixes #138 

---
If you are working on adding recordings for the new tests, please do the following:

- checkout the `record_set_support` branch from AnalogJ/lexicon
- then run `py.test tests/providers/test_memset.py` to generate the updated recordings. Read `CONTRIBUTING.md` for getting your dev environment setup. 
- you may need to update the provider to add support for record sets before the tests pass correctly.
- add any new files created in the `tests/fixtures/cassettes/{PROVIDER_NAME}/` directory. 
- open a PR against `record_set_support`

I wrote a cleanup script in tests/cleanup.sh that you can use to remove any existing DNS records in your account (just change the Provider name).

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/190)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by trinopoty** [comment]
I'll try to add linode recordings sometime later today.

**Comment by trinopoty** [comment]
Opened #193 for linode recordings.

**Comment by ppmathis** [comment]
I'm currently on the move but will gladly test the changes from @trinopoty and provide updated recordings for the ClouDNS provider by the end of this upcoming weekend.

**Comment by joostdebruijn** [comment]
I will test the changes later today and submit the new recordings afterwards for AuroraDNS.

**Comment by tnwhitwell** [comment]
I'll test Memset later on today!

**Comment by trinopoty** [comment]
Added nsone recordings here #199

**Comment by TyBrown** [comment]
Just wanted to say a quick THANK YOU to everyone who helped with this... I'm using Certbot with the DNSimple plugin, and after upgrading to 2.2.0 of Lexicon, I can report that the challenges and cleanup process worked flawlessly. I really appreciate the work, and how quickly this was fixed!

**Pull request merged**
