### PR TITLE
add support for Gandi LiveDNS API

### PR DESCRIPTION
**Pull request by sumpfralle**
Gandi currently provides the old (xmlrpc-based) and the new (REST-like) API for accessing the domain.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/162)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Hey
Thanks for the PR!
I like the idea of using the latest API for Gandi, but I'm not sure it makes sense to create a whole new provider for it.

Is there any advantage to keeping the old RPC based one? Is the output the same for both API's? It may be better to just replace the code in the existing Gandi provider. 

Also, I noticed that there are no VCR recordings in your PR. You'll need to include them before I can merge this. Check CONTRIBUTING.md for instructions.

**Comment by sumpfralle** [comment]
Thank you for mentioning the VCR recording - I will prepare one. This kind of data logging looks like a very good approach to me!

Regarding old vs. new Gandi API: Gandi uses both at the moment. For every single domain (zone) every user has to decide if he wants to use the new or the old API. It is not possible to use both the old and the new API with the same zone. In fact: Gandi seems to run two distinct set of nameservers for both APIs. Thus I am bit reluctant to force users to change the API of a zone in order to keep using lexicon.
But this is up to you: if you think, that is the right approach, then I will change my commits accordingly.

**Comment by AnalogJ** [comment]
Hey @sumpfralle 
Im glad you appreciate the testing pattern :) It's the only way I could think of to develop/maintain multiple providers (some of which require paid accounts) while still ensuring backwards compatibility. 

>  For every single domain (zone) every user has to decide if he wants to use the new or the old API.

Ugh, that's not what I expected at all. Good to know. Lets keep them as 2 seperate providers for now, though I'm not sure if `gandi_live` is going to work as a valid provider name. We might need to change it to `gandilive`or `gandirest`

**Comment by AnalogJ** [comment]
hey @sumpfralle 
I just wanted to check and see if you needed any help?

**Comment by adferrand** [comment]
Hello!

As I developed the original Gandi provider with RPC protocol, I would like to participate. 

For another provider, OVH, I made an additional parameter, the entrypoint, because OVH uses different base url depending on the DNS domain server location (America or Europe) and on the service level (Kimsufi, SoYouStart or OVH).

We could merge the two providers, and make a parameter to select the protocol, REST or RPC. RPC if not specified, and we move the default to Rest when Gandi shuts down RPC. 

What do you think about that?

**Comment by sumpfralle** [comment]
I would appreciate this approach. The thought of having two separate plugins for one provider feels a bit wrong.

Please feel free to do this - otherwise I would take a look at the OVH plugin.

**Comment by AnalogJ** [comment]
Yeah, I like the idea of having one provider per file, however the tests may require some tweaking if the api's are significantly different and talk to completely different endpoints.

Basically I'd like to have recordings for both endpoints, and the test suite as its defined right now doesn't support that out of the box, but could with a bit of tweaking:


```
# Test for one implementation of the interface
from lexicon.providers.gandi import Provider
...

class GandiRPCProviderTests(TestCase, IntegrationTests):

    Provider = Provider
    provider_name = 'gandi'
    domain = 'reachlike.ca'

   # Override _test_options to call env_auth_options and then import auth config from env variables
    def _test_options(self):
        cmd_options = super(GandiRPCProviderTests, self)._test_options()
        cmd_options.update({'endpoint_type':'rpc'})
        return cmd_options

    def _cassette_path(self, fixture_subpath):
        return "{0}/rpc/{1}".format(self.provider_name, fixture_subpath)

class GandiLiveProviderTests(TestCase, IntegrationTests):

    Provider = Provider
    provider_name = 'gandi'
    domain = 'reachlike.ca'

   # Override _test_options to call env_auth_options and then import auth config from env variables
    def _test_options(self):
        cmd_options = super(GandiLiveProviderTests, self)._test_options()
        cmd_options.update({'endpoint_type':'live'})
        return cmd_options
    def _cassette_path(self, fixture_subpath):
        return "{0}/live/{1}".format(self.provider_name, fixture_subpath)
```

Hopefully that makes sense. I can help with that part once the merged provider is closer to completion. 

Thanks for helping out with this one guys, I don't have a Gandi account so its basically impossible for me to work on this :(

**Comment by AnalogJ** [comment]
closes #171

**Comment by drzraf** [comment]
anything missing?

**Comment by AnalogJ** [comment]
I think @sumpfralle and @adferrand were going to work on merging this PR into a single provider, with a flag to choose the LIVE api vs the RPC api.

**Comment by mt7479** [comment]
@drzraf You can use the new provider as is if you're in desperate need. Just copy it to your lexcion providers directory, set the variables etc. I used it in conjunction with dehydrated.

If have one issue tho, if i try to list entries for my domain i recveive the following traceback:

``` 
lexicon gandi2 list example.com TXT

Traceback (most recent call last):
  File "/home/foo/.local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/home/foo/.local/lib/python2.7/site-packages/lexicon/__main__.py", line 69, in main
    client.execute()
  File "/home/foo/.local/lib/python2.7/site-packages/lexicon/client.py", line 44, in execute
    return self.provider.list_records(self.options.get('type'), self.options.get('name'), self.options.get('content'))
  File "/home/foo/.local/lib/python2.7/site-packages/lexicon/providers/gandi2.py", line 96, in list_records
    query_results = [item for item in query_results if item['type'] == type]
KeyError: 'type'
```

**Comment by jounisuo** [comment]
@mt7479 if you edit that line:
 query_results = [item for item in query_results if item['type'] == type]
to
 query_results = [item for item in query_results if item['rrset_type'] == type]

... You'll get rid of the error

**Comment by AnalogJ** [comment]
Hey @sumpfralle, @adferrand

I just wanted to follow up and see how this was going. Is there anything I can do to help?

**Comment by sumpfralle** [comment]
I just postponed the topic - sorry. I will do it in the next days ...

**Comment by adferrand** [comment]
Hello, sorry, I was really busy recently, so I could not work on this issue ... I will try to be available for next days.

**Comment by someburner** [comment]
I must be missing something cause this doesn't work for me at all.

My script:

```sh
#!/bin/bash

# not my email- but that doesnt work either
LEXICON_GANDI2_USERNAME="myusername"
# freshly generated token
LEXICON_GANDI2_TOKEN="xxxxxxxxxxxxxxxxxxxxxxxxxxxx"

_DOMAIN="some.domain"

lexicon gandi2 list $_DOMAIN TXT

exit 0;
```

Spits out:

```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://dns.api.gandi.net/api/v5/domains/some.domain
```

**Comment by joanfon** [comment]
Can someone solve this conflict? looks like it's only a problem in README.md file

**Comment by AnalogJ** [comment]
FYI, with the release of `v2.4.0` GoDaddy should be working again, thanks to @adferrand

**Comment by KoenR3** [comment]
Can someone resolve the issue?  I need to upgrade to v5 for several reasons and my letsencrypt is not working.  I would prefer not to diverge from the officially maintained lexicon by manually starting to install things...

**Comment by adferrand** [comment]
In fact I made the PR #247 which merges the two gandi providers (livedns and rpc) with some additional corrections to respect API specifications given by the integration tests. I think it will be integrated soon.

**Comment by AnalogJ** [comment]
FYI, with the release of v2.4.1 GoDaddy now supports REST and LIVE api's. 
Thanks again @adferrand! 🎉

**Pull request merged**
