### PR TITLE
Support more python versions

### PR DESCRIPTION
**Pull request by deadNightTiger**
Used `futurize` script from http://python-future.org and cleaned up some errors made by it. This adds dependency on `future`, but I believe it's worth.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](http://www.github.com/AnalogJ/capsulecd). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](http://www.capsulecd.com/#!/deploy/github/AnalogJ/lexicon/pullrequests/39)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](http://www.github.com/AnalogJ/capsulecd)

**Comment by AnalogJ** [comment]
Hey @deadNightTiger I'll take a look. I definitely wanted to add support for other versions of python but I never got around to it.  I'm not really familiar with `futurize` or the differences in python3 and python2.6. From your PR it seems that the changes are mostly related to `print`, `StandardError` and class definitions. Is there a way to just manually handle those few differences without adding another dependency?

I'm more than happy to merge your PR if not.

**Comment by deadNightTiger** [comment]
You could, but python 2.6 doesn't have `importlib` (which `future` provides), and python 2 and 3 have different arguments on `bytes` constructor (`future` has a wrapper around that).

**Comment by AnalogJ** [comment]
Hey @deadNightTiger 
Sorry for keeping this PR open for so long. Honestly everytime I see it I internally start debating on if I want to add another top-level dependency to the project. 

Now that I've started adding optional provider-specific dependencies (like boto for route53) this might be impossible. 

I'll definitely try to spend some time next week to bring this PR back up-to-date.

**Pull request closed without merging**
