### PR TITLE
Change example letsencrypt.sh hook

### PR DESCRIPTION
**Pull request by osiux**
Not sure if needed, but I updated my hook script to adhere to the [letsencrypt.sh hook example](https://github.com/lukas2511/letsencrypt.sh/blob/master/hook.sh.example).

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](http://www.github.com/AnalogJ/capsulecd). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](http://www.capsulecd.com/#!/deploy/github/AnalogJ/lexicon/pullrequests/15)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](http://www.github.com/AnalogJ/capsulecd)

**Comment by AnalogJ** [comment]
:+1: LGTM.

**Comment by CapsuleCD** [comment]
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](http://www.github.com/AnalogJ/capsulecd)

**Comment by CapsuleCD** [comment]
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](http://www.github.com/AnalogJ/capsulecd)

**Comment by AnalogJ** [comment]
sorry @osiux I'm just working on some automation that's supposed to merge this PR for me.. its obviously not working correctly :)

**Comment by osiux** [comment]
No worries!

**Comment by CapsuleCD** [comment]
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](http://www.github.com/AnalogJ/capsulecd)

**Comment by AnalogJ** [comment]
looks like I finally got this working. Thanks for the PR @osiux, merged as v1.0.15

**Pull request merged**
