### PR TITLE
Use relative domain instead of full domain with dnsimple

### PR DESCRIPTION
**Pull request by osiux**
Hi! I stumbled upon the same bug of #3 and I tried to fix it. I made some tests and seems to work fine. I'm not a python developer so I'm sorry if this is not the most efficient way to do it, but I hope it gives an idea. It would be awesome if it can be fixed in the lib!

Regards

### CODE REVIEW

**Comment by AnalogJ** [comment]
Hey, thanks for the PR. 
I'll take a look at it and merge it tomorrow after I take a look :)

**Comment by AnalogJ** [comment]
Hey @osiux can you try using version v1.0.11 now? I made a bunch of fixes and wrote a full test suite to verify that all the providers work in the same way. DNSimple should be working correctly now.

**Comment by osiux** [comment]
Hey @AnalogJ! I just had a chance to test v1.0.11, but it doesn't seem to be working, same problem :(

The record for the bare domain is still being created as: _acme-challenge.domain.com.domain.com

And for the subdomain: _acme-challenge.www.domain.com.domain.com

selection_044

And since the record is not found, it's also not deleting it after it fails.

```
./letsencrypt.sh -c -x
# INFO: Using main config file /root/letsencrypt/config.sh
Processing domain.com with alternative names: www.domain.com
 + Checking domain name(s) of existing cert... changed!
 + Domain name(s) are not matching!
 + Names in old certificate: domain.com
 + Configured names: domain.com www.domain.com
 + Forcing renew.
 + Checking expire date of existing cert...
 + Valid till Jun  X XX:XX:XX 2016 GMT (Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating signing request...
 + Requesting challenge for domain.com...
 + Requesting challenge for www.domain.com...
deploy_challenge called: deploy_challenge, domain.com, challengestring, challengestring
Namespace(action='create', auth_otp_token=None, auth_password=None, auth_token=None, auth_username=None, content='challengestring', domain='domain.com', identifier=None, name='_acme-challenge.domain.com.', priority=None, provider_name='dnsimple', ttl=None, type='TXT')
create_record: True
 + Responding to challenge for domain.com...
clean_challenge called: clean_challenge, domain.com, challengestring, challengestring
Namespace(action='delete', auth_otp_token=None, auth_password=None, auth_token=None, auth_username=None, content='challengestring', domain='domain.com', identifier=None, name='_acme-challenge.domain.com.', priority=None, provider_name='dnsimple', ttl=None, type='TXT')
list_records: []
[]
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==1.0.11', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 38, in main
    client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 43, in execute
    return self.provider.delete_record(self.options.get('identifier'), self.options.get('type'), self.options.get('name'), self.options.get('content'))
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/dnsimple.py", line 96, in delete_record
    raise StandardError('Record identifier could not be found.')
StandardError: Record identifier could not be found.
```

It's weird, but maybe the behavior in the dnsimple sandbox is different that the one in production?

**Comment by osiux** [comment]
I just noticed something, not sure if it has anything to do with this.

In the [test suite](https://github.com/AnalogJ/lexicon/blob/46dc7ba6e7bc8869abf2052f23cd52545409e29e/tests/fixtures/cassettes/dnsimple/IntegrationTests/test_Provider_when_calling_create_record_for_TXT_with_fully_qualified_name_and_content.yaml#L48), the domain is being sent as **_acme-challenge.www.capsulecd.com**, while in the library (or at least in the log i put in my other comment) it's sent as **_acme-challenge.domain.com.**

Maybe that last dot is part of the problem? Although I thik DNS requires just the relative domain name.

**Comment by AnalogJ** [comment]
hey @osiux 
You were correct, full and fqdn domains were causing issues with dnsimple. I've cleaned up the provider and added a new set of integration tests so that other providers don't run into the same issue. Can you try version v1.0.12 now?

**Comment by osiux** [comment]
I just tested it and it's working flawlesly, awesome!

This can be closed now, thank you!

**Comment by AnalogJ** [comment]
perfect. closing :)

**Pull request closed without merging**
