### PR TITLE
Add support for record sets in Route53

### PR DESCRIPTION
**Pull request by danoh**
Hello,
I was able to issue certificate for example.com and *.example.com domain using this patch.
Probably it can help someone, even if I it is quite dirty, I am not happy about the test:

`if (isinstance(existing_records[0]['content'],list)):`

it will probably fail if there will be more records returned.

### CODE REVIEW

**Comment by AnalogJ** [comment]
Hey @danoh 
This is a great start. Route53 record sets have been a priority for me for a while. 

There's an optional test suite available for record sets that can be used to validate that everything is working correctly, but its currently disabled for `route53`. 

Could you enable it, verify that the tests pass and then include the updated route53 recordings in your PR? That way we can confirm that everything is working as intended.

Here are the steps:
- Follow the [CONTRIBUTING.md](https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md) to get your dev environment ready
- Uncomment this file: https://github.com/AnalogJ/lexicon/blob/master/tests/providers/test_route53.py#L1-L46 
- Test the provider using the instructions Contributing.md

If theres anything you have questions about, feel free to get in touch.

**Comment by danoh** [comment]
Hi @AnalogJ 

it looks, that the test has to be performed against you own zone on AWS? In the file IntegrationTests/test_Provider_authenticate.yaml are IDs which I don't have access to. And just changing the domain name in test_route53.py seems be not working, I am getting test errors with my credentials even if the lexicon itself can create/update/delete the domain.

The yaml file is autogenerated?

**Comment by AnalogJ** [comment]
Hey @danoh 
Yeah those yaml files (cassettes) are automatically generated by vcr-py. You can delete them for the route53 provider and they can be regenerated with your credentials and domain. 

`https://github.com/AnalogJ/lexicon/tree/master/tests/fixtures/cassettes/route53/IntegrationTests` - delete that directory

Don't worry, credentials, api keys and passwords should be ignored by the configuration in the tests file. 

https://github.com/AnalogJ/lexicon/blob/master/tests/providers/test_route53.py#L14-L16

**Comment by danoh** [comment]
Hi @AnalogJ 

so the question is - how can I supply the auth_access_key and auth_access_secret for the test?

**Comment by AnalogJ** [comment]
You'll need to set the following environmental variables:
```
export LEXICON_LIVE_TESTS=true
export LEXICON_ROUTE53_ACCESS_KEY=""
export LEXICON_ROUTE53_ACCESS_SECRET=""
```

And you'll need to uncomment this file and set the domain to one you have access to:
https://github.com/AnalogJ/lexicon/blob/master/tests/providers/test_route53.py#L12

If you've already followed [CONTIRBUTING.md](https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md) you can just run:

`py.test tests/providers/test_route53.py`

**Comment by danoh** [comment]
great, this way seems be working:
20 passed, 10 skipped, 1 warnings in 22.78 seconds
the warning is about "InsecureRequestWarning: Unverified HTTPS request is being made"

**Comment by adferrand** [comment]
This warning occurs typically on Python 2.7 when the module `requests` is installed without some ssl modules dependencies. That can be installed via `pip install requests[security]`, or `pip install -e .` from lexicon project root folder, because lexicon declares `requests[security]` as a dependencies.

Then this warning will vanish.

**Comment by AnalogJ** [comment]
Great @danoh 
Now that you've gotten the test suite enabled and working, you'll need to enable the record-sets test suite so that we can validate that your change works. 

Can you remove the following lines:
https://github.com/AnalogJ/lexicon/blob/master/tests/providers/test_route53.py#L38-L46

and then re-run the test suite locally?

**Comment by adferrand** [comment]
Hello @danoh, it seems that your PR is quite complete, and only requires to fix conflict and enabling the full test suite to execute tests against recordset.

Will you have the time to handle this?

**Comment by danoh** [comment]
Hello @adferrand,

it is not so simple, I am not able to pass all the tests. It works fine for Let's Encrypt usage, but fails if the domain has some other records of the same type, like google domain validation. This situation is not covered by the testing suite, I figured it out by recognising, that I am missing TXT records on my domains. So I don't suggest to merge this now, but I don't know when I will be able to  find time to rewrite it.
The problematic situation is like:

first.example.com. TXT aaa
second.first.example.com. TXT bbb
third.second.first.example.com. TXT ccc

you won't be able to add second TXT value to third.second.first.example.com. and remove it without touching the first two records.

**Comment by adferrand** [comment]
So I assume that `test_Provider_when_calling_delete_record_with_record_set_by_content_should_leave_others_untouched` is failing because removing a TXT record for a given name, removes all TXT records for that name, no only the TXT record of the content that has been specified.

I assume also from what you said, that it also remove TXT records for all top-level domains of a given name (meaning one.two.example.com action also impact two.example.com). I am quite surprised by this behavior, as it seems from the provider code that the JSON passed to make an action contains a `name` field, so I would expect that only one particular `name` value would be impacted. 

But maybe I am wrong, and not that surprised as I have experienced myself some nightmare APIs for Lexicon ^^

**Comment by adferrand** [comment]
Nevertheless what is more important is that your work leads to something. And your work, even if it does not allow a proper cleaning of inserted records, allows to execute the logic required to make dns challenges for wildcard certificates.

So if you do not have the time to complete the delete operation, I suggest you to make delete actions a noop operation if we are in a recordset situation, skip the relevant existing tests, maybe add a custom test to ensure the noop operation, and let a future you or another contributor finish the job.

**Comment by AnalogJ** [comment]
I second @adferrand 's idea. Record set support for Route53 is a huge gap for us. Getting a partial solution up and running will the a huge step forward, and we can work on enhancing your work afterwards.

**Comment by AnalogJ** [comment]
Hey @danoh I see that you are working on the Route53 branch. I wouldn't worry too much about making PyLint happy. The main thing that we're looking for is enabling the extended test suite (https://github.com/AnalogJ/lexicon/blob/master/tests/providers/test_route53.py#L14-L16) and creating new recordings. 

Thanks for picking this up again!

**Comment by danoh** [comment]
Hi, i see, that there are some changes in the code and I am currently unable to start any test at all. 
There is syntax error on line 22 of the test_route53.py file, if I fix it, it is unable to import provider_vcr and this is currently stop for me, while I don't see the definition anywhere.

**Comment by adferrand** [comment]
Hello @danoh. Indeed tests for Route53 were entirely commented out, so they have not been refactored regarding the changes we did recently.

I fixed them and pushed to master. Now there are not commented out, just skipped. The tests are functional, the cassettes just need to be regenerated with a valid account. 

You can follow:
* https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md#testing-your-provider for general description of the integration tests,
* https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md#test-recordings to see how to execute live tests and regenerate the cassettes,
* https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md#skipping-testssuites to check about disabled tests suite in the provider integration tests.

**Comment by danoh** [comment]
OK, basic test are working fine, from disabled test is failing
Route53ProviderTests.test_provider_when_calling_create_record_with_duplicate_records_should_be_noop
Route53ProviderTests.test_provider_when_calling_delete_record_with_record_set_name_remove_all
Route53ProviderTests.test_provider_when_calling_list_records_should_handle_record_sets
i will check later why, the first one is obvious, R53 API doesn't accept batch with duplicate commands.

**Comment by adferrand** [comment]
Hello @danoh. I finally took the time to setup myself an AWS account, and fix the remaining problems in your PR. It was mainly about handling correctly noop on duplicate records, and record sets for update operations.

This is now good, so I merge it!

**Pull request merged**
