### PR TITLE
fix godaddy update and delete actions

### LINKED ISSUE #1019: godaddy: can't delete records HTTPError: 422 Client Error: Unprocessable Entity for url
`$ lexicon godaddy --auth-key <key> --auth-secret <secret> delete <domain> TXT --name '<name>'` results in:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/lexicon", line 33, in <module>
    sys.exit(load_entry_point('dns-lexicon==3.8.3', 'console_scripts', 'lexicon')())
  File "/usr/lib/python3.9/site-packages/lexicon/cli.py", line 131, in main
    results = client.execute()
  File "/usr/lib/python3.9/site-packages/lexicon/client.py", line 97, in execute
    return self.provider.delete_record(identifier, record_type, name, content)
  File "/usr/lib/python3.9/site-packages/lexicon/providers/base.py", line 118, in delete_record
    return self._delete_record(
  File "/usr/lib/python3.9/site-packages/lexicon/providers/godaddy.py", line 261, in _delete_record
    self._put(f"/domains/{domain}/records", filtered_records)
  File "/usr/lib/python3.9/site-packages/lexicon/providers/base.py", line 189, in _put
    return self._request("PUT", url, data=data, query_params=query_params)
  File "/usr/lib/python3.9/site-packages/lexicon/providers/godaddy.py", line 328, in _request
    result.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/<domain>/records
```

### PR DESCRIPTION
**Pull request by zeule**
Fixes #1019.

### CODE REVIEW

**Review by adferrand — CHANGES_REQUESTED** [review]
Hello @zeule !

Sorry for the delay on my answer. I tried to reproduce your issue, but run your scenario without issue:
```bash
$ lexicon godaddy create <domain> TXT --name test --content test1                                         12/28/21 -  6:43 PM
RESULT
------
True
$ lexicon godaddy list <domain> TXT                                                                       12/28/21 -  6:44 PM
ID      TYPE NAME                    CONTENT TTL
------- ---- ----------------------- ------- ----
a88948d TXT  <domain> test1   3600
$ lexicon godaddy delete <domain> TXT --name test                                                         12/28/21 -  6:44 PM
RESULT
------
True
```

I also looked at your PR. Running the integration tests, I see the following tests failing:
```
FAILED lexicon/tests/providers/test_godaddy.py::GoDaddyProviderTests::test_provider_when_calling_delete_record_with_record_set_by_content_should_leave_others_untouched
FAILED lexicon/tests/providers/test_godaddy.py::GoDaddyProviderTests::test_provider_when_calling_delete_record_with_record_set_name_remove_all
FAILED lexicon/tests/providers/test_godaddy.py::GoDaddyProviderTests::test_provider_when_calling_update_record_should_modify_record
FAILED lexicon/tests/providers/test_godaddy.py::GoDaddyProviderTests::test_provider_when_calling_update_record_with_fqdn_name_should_modify_record
FAILED lexicon/tests/providers/test_godaddy.py::GoDaddyProviderTests::test_provider_when_calling_update_record_with_full_name_should_modify_record
```

By the way, I advise you to run these integration tests and update the recordings in this PR accordingly. The relevant section in the developer guide is here: https://dns-lexicon.readthedocs.io/en/latest/developer_guide.html#testing-your-provider

**Comment by zeule** [comment]
@adferrand, I'm using version 3.8.3 here (python 3.9, Gentoo x86_64) and deleting does not work, just tested it again. I'm happy to hear that the problem seems to be fixed in the master branch. 

As for the integration tests, I'm not a python developer and not going to setup a dev environment. The automatic test updating is not possible with system packages on Gentoo, unfortunately, (as far as I can remember there is a version mismatch for some dependency between the system and lexicon), and I do not want to update all the tests manually.

**Comment by adferrand** [comment]
Indeed, I could reproduce an issue with the update action, that I fixed on the current implementation. So this part should be fixed even if there is some unresolved issues with other tests on the master branch also.

So far, if I do a release with the current state of master, is it solving all your problems?

**Comment by zeule** [comment]
If memory serves me well, the problem with the delete action manifested itself, and this is why I changed the way it works here from updating the whole domain record set to using the API call for delete, when the domain contains the "@" record (), which can not be updated.

**Comment by adferrand** [comment]
Ok. I create a new release then, since it is improving the situation, and I will see with your PR to rerun the integration tests once they are fixed in the master branch.

**Comment by zeule** [comment]
Thank you!

**Comment by zeule** [comment]
For the record, update and delete actions with 3.8.4 fail with `requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/<domain>/records/TXT/<name>`.

**Comment by adferrand** [comment]
Yes I just release Lexicon 3.8.5, with a complete redesign of the update and delete actions on the godaddy provider. All tests are now passing on the live API, I have good hope that it fixes the unprocessable entity errors.

**Comment by zeule** [comment]
Update and delete actions work here with 3.8.5. Thank you!

**Pull request closed without merging**
