### PR TITLE
Added support for Linode

### PR DESCRIPTION
**Pull request by trinopoty**
This implements the Linode dns api.

### CODE REVIEW

**Comment by CapsuleCD** [comment]
Hi.

I'm an automated pull request bot named [CapsuleCD](https://www.capsulecd.com). I handle testing, versioning and package releases for this project. 
- If you're the owner of this repo, you can click the button below to kick off the CapsuleCD build pipeline and create an automated release.'
- If not, don't worry, someone will be by shortly to check on your pull request. 

[CapsuleCD](https://www.capsulecd.com/project/github/AnalogJ/lexicon/pullrequests/156)

---
If you're interested in learning more about [CapsuleCD](http://www.github.com/AnalogJ/capsulecd), or adding it to your project, you can check it out [here](https://www.capsulecd.com)

**Comment by AnalogJ** [comment]
Awesome, thanks for the PR!
I'll take a look at it and merge it later today.

**Comment by trinopoty** [comment]
I forgot to change the readme. It still indicates no support for Linode. Can you please update the readme to indicate support for Linode DNS.

**Comment by AnalogJ** [comment]
Added to readme. Thanks again for your PR @trinopoty

**Pull request merged**
